services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: immotrack
      POSTGRES_PASSWORD: immotrack
      POSTGRES_DB: immotrack
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
